import "@fortawesome/fontawesome-svg-core/styles.css"
import "./globals.css";

import { Montserrat } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core"

import Header from "./components/Header/Header";

config.autoAddCss = false

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
